package com.usanaem.occultic_ntm.compat.thaumcraft.aspect.catalogue;

import com.hbm.items.ModItems;
import static com.usanaem.occultic_ntm.compat.thaumcraft.aspect.catalogue.CatalogueHelper.*;

public final class EquipmentCatalogue {

    private EquipmentCatalogue() { }

    public static void register() {
        registerHazmat();
        registerArmor();
        registerTools();
        registerMedical();
    }

    private static void registerHazmat() {
        regWildcard(ModItems.hazmat_boots, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_boots_grey, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_boots_red, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_cloth, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_cloth_grey, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_cloth_red, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_grey_kit, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_helmet, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_helmet_grey, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_helmet_red, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_kit, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_legs, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_legs_grey, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_legs_red, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_paa_boots, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_paa_helmet, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_paa_legs, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_paa_plate, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_plate, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_plate_grey, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_plate_red, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
        regWildcard(ModItems.hazmat_red_kit, a("tutamen", 4, "radio", 3, "contaminatio", 3, "chemica", 2));
    }

    private static void registerArmor() {
        regWildcard(ModItems.ajr_boots, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.ajr_helmet, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.ajr_legs, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.ajr_plate, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.ajro_boots, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.ajro_helmet, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.ajro_legs, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.ajro_plate, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.asbestos_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.asbestos_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.asbestos_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.asbestos_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.ashglasses, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.bismuth_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.bismuth_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.bismuth_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.bismuth_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.bj_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.bj_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.bj_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.bj_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.bj_plate_jetpack, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.cmb_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.cmb_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.cmb_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.cmb_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.cobalt_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.cobalt_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.cobalt_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.cobalt_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dieselsuit_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dieselsuit_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dieselsuit_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dieselsuit_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dns_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dns_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dns_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dns_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dnt_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dnt_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dnt_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.dnt_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.envsuit_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.envsuit_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.envsuit_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.envsuit_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.euphemium_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.euphemium_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.euphemium_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.euphemium_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.fau_boots, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.fau_helmet, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.fau_legs, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.fau_plate, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.gas_mask, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.gas_mask_m65, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.gas_mask_mono, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.gas_mask_olde, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.goggles, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.hat, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.hev_boots, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.hev_helmet, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.hev_legs, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.hev_plate, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.liquidator_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.liquidator_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.liquidator_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.liquidator_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.ncrpa_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.ncrpa_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.ncrpa_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.ncrpa_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.no9, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.paa_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.paa_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.paa_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_aluminium, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_armor_ajr, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.plate_armor_dnt, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_armor_fau, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.plate_armor_hev, a("tutamen", 6, "electrum", 4, "machina", 4, "metallum", 4));
        regWildcard(ModItems.plate_armor_lunar, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_armor_titanium, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.plate_bismuth, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_cast, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_combine_steel, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.plate_copper, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_dalekanium, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_desh, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_dineutronium, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_dura_steel, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.plate_euphemium, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_gold, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_gunmetal, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_iron, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_kevlar, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_lead, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_mixed, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_paa, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_polymer, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_saturnite, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_schrabidium, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.plate_steel, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.plate_titanium, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.plate_weaponsteel, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.plate_welded, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.robes_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.robes_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.robes_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.robes_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.rpa_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.rpa_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.rpa_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.rpa_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.schrabidium_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.schrabidium_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.schrabidium_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.schrabidium_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.security_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.security_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.security_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.security_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.stamp_desh_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.stamp_iron_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.stamp_obsidian_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.stamp_steel_plate, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.stamp_stone_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.stamp_titanium_plate, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.starmetal_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.starmetal_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.starmetal_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.starmetal_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.steamsuit_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.steamsuit_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.steamsuit_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.steamsuit_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.steel_boots, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.steel_helmet, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.steel_legs, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.steel_plate, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.t51_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.t51_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.t51_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.t51_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.taurun_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.taurun_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.taurun_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.taurun_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.template_folder, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.titanium_boots, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.titanium_helmet, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.titanium_legs, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.titanium_plate, a("tutamen", 4, "metallum", 3));
        regWildcard(ModItems.trenchmaster_boots, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.trenchmaster_helmet, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.trenchmaster_legs, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.trenchmaster_plate, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.upgrade_template, a("tutamen", 3, "metallum", 2));
        regWildcard(ModItems.zirconium_legs, a("tutamen", 3, "metallum", 2));
    }

    private static void registerTools() {
        regWildcard(ModItems.analysis_tool, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.bismuth_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.bismuth_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.blowtorch, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.centri_stick, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.chainsaw, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.chlorophyte_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.chlorophyte_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.cmb_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.cmb_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.cmb_shovel, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.cobalt_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.cobalt_decorated_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.cobalt_decorated_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.cobalt_decorated_shovel, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.cobalt_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.cobalt_shovel, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.coupling_tool, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.crowbar, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.desh_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.desh_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.desh_shovel, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.dosimeter, a("sensus", 4, "radio", 3, "electrum", 2, "machina", 2));
        regWildcard(ModItems.drill_titanium, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.drillbit, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.dwarven_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.elec_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.elec_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.elec_shovel, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.geiger_counter, a("sensus", 4, "radio", 3, "electrum", 2, "machina", 2));
        regWildcard(ModItems.gun_drill, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.hand_drill, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.hand_drill_desh, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.mese_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.mese_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.mirror_tool, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.missile_drill, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.powder_sawdust, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.power_net_tool, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.rbmk_tool, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.sawblade, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.schrabidium_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.schrabidium_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.schrabidium_shovel, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.screwdriver, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.screwdriver_desh, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.settings_tool, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.smashing_hammer, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.starmetal_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.starmetal_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.starmetal_shovel, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.steel_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.steel_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.steel_shovel, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.titanium_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.titanium_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.titanium_shovel, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.toolbox, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.volcanic_axe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.volcanic_pickaxe, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.wrench, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.wrench_archineer, a("instrumentum", 3, "metallum", 2));
        regWildcard(ModItems.wrench_flipped, a("instrumentum", 3, "metallum", 2));
    }

    private static void registerMedical() {
        reg(ModItems.pill_herbal, a("sano", 4, "victus", 2, "chemica", 1));
        reg(ModItems.pill_iodine, a("sano", 4, "radio", 2, "contaminatio", 2, "chemica", 2));
        reg(ModItems.pill_red, a("sano", 4, "victus", 2, "chemica", 1));
        reg(ModItems.powder_iodine, a("sano", 4, "radio", 2, "contaminatio", 2, "chemica", 2));
        reg(ModItems.radaway, a("sano", 4, "radio", 2, "contaminatio", 2, "chemica", 2));
        reg(ModItems.radaway_flush, a("sano", 4, "radio", 2, "contaminatio", 2, "chemica", 2));
        reg(ModItems.radaway_strong, a("sano", 4, "radio", 2, "contaminatio", 2, "chemica", 2));
        reg(ModItems.radx, a("sano", 4, "radio", 2, "contaminatio", 2, "chemica", 2));
        reg(ModItems.syringe_metal_stimpak, a("sano", 4, "victus", 2, "chemica", 1));
    }
}
